import { describe, expect, it } from "vitest";
import { formatArtifactReferencesForSharedContext } from "../tools/sub-agent.js";

// Run 663ac153 regression: ~50 questions were authored 3× across successive delegated agents.
// Artifacts a sub-agent produces are ALREADY surfaced to later agents via the shared partial-results
// context (appendPartialResult stores this formatter's output after the summary), but by default as a
// PASSIVE list — so agents re-authored instead of reusing. The crossAgentArtifactReuse directive
// (config-gated at the call site; here the boolean is passed directly) turns that same list into an
// explicit "read + reuse/extend, do NOT re-author" instruction. Structural: artifact paths only.

describe("formatArtifactReferencesForSharedContext — cross-agent reuse directive", () => {
  const artifacts = [
    { outputPath: "generated/questions.json", sourceTool: "write_file", previewMode: "code" },
    { outputPath: "generated/report.md", sourceTool: "write_file" },
  ];

  it("emits the PASSIVE list by default (directive off) — unchanged legacy behavior", () => {
    const out = formatArtifactReferencesForSharedContext(artifacts);
    expect(out).toContain("Artifacts generated by this result:");
    expect(out).toContain("- generated/questions.json (code, write_file)");
    expect(out).toContain("- generated/report.md (write_file)");
    expect(out).not.toMatch(/re-author/i);
  });

  it("emits an actionable REUSE directive when the flag is on", () => {
    const out = formatArtifactReferencesForSharedContext(artifacts, true);
    expect(out).toMatch(/READ \(read_file\) and REUSE\/EXTEND/i);
    expect(out).toMatch(/instead of re-authoring/i);
    // the artifact paths are still listed so a later agent can open them
    expect(out).toContain("- generated/questions.json (code, write_file)");
    expect(out).toContain("- generated/report.md (write_file)");
  });

  it("returns an empty string when there are no real artifacts (both modes)", () => {
    expect(formatArtifactReferencesForSharedContext([])).toBe("");
    expect(formatArtifactReferencesForSharedContext([{ foo: "bar" }], true)).toBe("");
  });

  it("caps the surfaced list at 6 artifacts to bound the injected context", () => {
    const many = Array.from({ length: 10 }, (_, i) => ({ outputPath: `generated/f${i}.txt`, sourceTool: "write_file" }));
    const out = formatArtifactReferencesForSharedContext(many, true);
    expect(out.match(/- generated\/f\d+\.txt/g)?.length).toBe(6);
  });
});
