import { createApp } from "vue";
import { createPinia } from "pinia";
import { registerSW } from "virtual:pwa-register";
import router from "./router";
import App from "./App.vue";
import { useThemeStore } from "./stores/theme";
// Self-hosted base fonts (the default "Clean" typeface). Bundled via @fontsource so
// first paint makes ZERO third-party font requests (GDPR + offline). Weights match
// the former Google Fonts @import. Every other typeface still loads its fonts lazily
// from its CDN only when the user selects it (see stores/theme.ts hrefs).
import "@fontsource/inter/300.css";
import "@fontsource/inter/400.css";
import "@fontsource/inter/500.css";
import "@fontsource/inter/600.css";
import "@fontsource/inter/700.css";
import "@fontsource/inter/800.css";
import "@fontsource/jetbrains-mono/400.css";
import "@fontsource/jetbrains-mono/500.css";
import "@fontsource/jetbrains-mono/600.css";
import "./style.css";

// Register the service worker generated by vite-plugin-pwa.  `immediate: true`
// activates the SW on first load (so a refresh isn't required to pick it up),
// and `autoUpdate` mode means new builds install in the background. Handle
// `onNeedRefresh` explicitly so stale bundles do not linger after deploys.
const updateSW = registerSW({
	immediate: true,
	onNeedRefresh() {
		if (typeof window === "undefined") return;
		const shouldReload = window.document.visibilityState === "hidden"
			|| window.confirm("A new StarlingAI UI build is available. Reload now?");
		if (shouldReload) void updateSW(true);
	},
	onRegisteredSW(_swUrl, registration) {
		if (!registration || typeof window === "undefined") return;
		window.setInterval(() => {
			void registration.update();
		}, 60_000);
	},
	onRegisterError(error) {
		console.error("Service worker registration failed:", error);
	},
});

const CHUNK_RELOAD_KEY = "starlingai:chunk-reload-target";

function isDynamicImportFailure(error: unknown): boolean {
	const message = error instanceof Error ? error.message : String(error ?? "");
	return /Failed to fetch dynamically imported module|Importing a module script failed|error loading dynamically imported module/i.test(message);
}

router.onError((error, to) => {
	if (!isDynamicImportFailure(error)) {
		console.error(error);
		return;
	}

	const target = to.fullPath || window.location.pathname + window.location.search + window.location.hash;
	const previousTarget = window.sessionStorage.getItem(CHUNK_RELOAD_KEY);
	if (previousTarget === target) {
		window.sessionStorage.removeItem(CHUNK_RELOAD_KEY);
		console.error(error);
		return;
	}

	window.sessionStorage.setItem(CHUNK_RELOAD_KEY, target);
	window.location.assign(target);
});

router.afterEach(() => {
	window.sessionStorage.removeItem(CHUNK_RELOAD_KEY);
});

const app = createApp(App);
// App-level error boundary: a thrown render/lifecycle error in one component is
// logged and contained here instead of tearing down the whole dashboard. (Vue
// still unmounts the failing subtree, but sibling views keep working.)
app.config.errorHandler = (err, _instance, info) => {
  console.error(`[vue] unhandled component error (${info}):`, err);
};
const pinia = createPinia();
app.use(pinia);
app.use(router);
// Apply the persisted theme before mount so a non-default theme doesn't flash
// the default palette on first paint.
useThemeStore(pinia).init();
app.mount("#app");
