import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

/**
 * Tiny PKZIP central-directory walker. We avoid installing a yauzl dev-dep
 * just for these tests. Each central-directory header is preceded by the
 * signature 0x02014b50 (PK\x01\x02). We scan from the end-of-central-dir
 * record, which lives near the end of the file.
 */
function listZipEntryNames(path: string): string[] {
  const buf = readFileSync(path);
  // Find end-of-central-directory record (signature 0x06054b50). It can be
  // anywhere in the last 64KB, but for our tiny test fixtures it's at the very
  // tail (no zip comment).
  let eocdrOffset = -1;
  for (let i = buf.length - 22; i >= Math.max(0, buf.length - 65535 - 22); i--) {
    if (buf.readUInt32LE(i) === 0x06054b50) {
      eocdrOffset = i;
      break;
    }
  }
  if (eocdrOffset === -1) throw new Error("EOCDR not found");
  const cdEntryCount = buf.readUInt16LE(eocdrOffset + 10);
  let cdOffset = buf.readUInt32LE(eocdrOffset + 16);
  const names: string[] = [];
  for (let i = 0; i < cdEntryCount; i++) {
    if (buf.readUInt32LE(cdOffset) !== 0x02014b50) {
      throw new Error("invalid central directory entry signature");
    }
    const nameLen = buf.readUInt16LE(cdOffset + 28);
    const extraLen = buf.readUInt16LE(cdOffset + 30);
    const commentLen = buf.readUInt16LE(cdOffset + 32);
    const name = buf.toString("utf8", cdOffset + 46, cdOffset + 46 + nameLen);
    names.push(name);
    cdOffset += 46 + nameLen + extraLen + commentLen;
  }
  return names;
}

describe("bundle_artifact_zip", () => {
  const cleanup: string[] = [];
  let workspace: string;

  beforeEach(() => {
    workspace = mkdtempSync(join(tmpdir(), "starlingai-bundle-"));
    cleanup.push(workspace);
  });

  afterEach(() => {
    for (const dir of cleanup.splice(0)) {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  async function getTool() {
    const [{ getTool }] = await Promise.all([
      import("./registry.js"),
      import("./bundle-zip.js"),
    ]);
    return getTool("bundle_artifact_zip")!;
  }

  function ctx() {
    return { sessionId: "s1", workspacePath: workspace };
  }

  function isPkZip(path: string): boolean {
    const buf = readFileSync(path);
    return buf[0] === 0x50 && buf[1] === 0x4B;
  }

  it("rejects when no entries are provided", async () => {
    const result = await (await getTool()).execute({ output_file: "out.zip" }, ctx());
    expect(result.success).toBe(false);
    expect(result.error).toContain("at least one");
  });

  it("rejects non-.zip output_file", async () => {
    const result = await (await getTool()).execute({
      output_file: "out.tgz",
      inline: [{ archivePath: "x.txt", content: "hi" }],
    }, ctx());
    expect(result.success).toBe(false);
    expect(result.error).toContain(".zip");
  });

  it("packs inline + workspace files into a valid zip with the expected entry names", async () => {
    writeFileSync(join(workspace, "report.md"), "# Report\nbody", "utf8");
    mkdirSync(join(workspace, "src"));
    writeFileSync(join(workspace, "src/main.ts"), "console.log('hi');", "utf8");

    const result = await (await getTool()).execute({
      output_file: "deliverable.zip",
      inline: [
        { archivePath: "README.txt", content: "Bundle generated by tests." },
        { archivePath: "data/payload.bin", content: Buffer.from([1, 2, 3, 4]).toString("base64"), encoding: "base64" },
      ],
      files: [
        { workspacePath: "report.md", archivePath: "docs/report.md" },
        { workspacePath: "src/main.ts" },
      ],
    }, ctx());

    expect(result.success).toBe(true);
    expect(result.metadata?.["entryCount"]).toBe(4);
    expect(result.metadata?.["format"]).toBe("zip");
    expect(result.metadata?.["artifactKind"]).toBe("document");
    expect(result.metadata?.["previewMode"]).toBe("download");

    const zipPath = join(workspace, "generated", "deliverable.zip");
    expect(isPkZip(zipPath)).toBe(true);
    expect(statSync(zipPath).size).toBeGreaterThan(0);

    const names = listZipEntryNames(zipPath).sort();
    expect(names).toEqual([
      "README.txt",
      "data/payload.bin",
      "docs/report.md",
      "src/main.ts",
    ]);
  });

  it("walks a directory entry recursively, honoring include/exclude globs", async () => {
    mkdirSync(join(workspace, "site"));
    mkdirSync(join(workspace, "site/docs"));
    writeFileSync(join(workspace, "site/index.html"), "<h1>i</h1>", "utf8");
    writeFileSync(join(workspace, "site/about.html"), "<h1>a</h1>", "utf8");
    writeFileSync(join(workspace, "site/secret.env"), "KEY=xyz", "utf8");
    writeFileSync(join(workspace, "site/docs/intro.html"), "<h1>intro</h1>", "utf8");
    writeFileSync(join(workspace, "site/docs/draft.html"), "<h1>draft</h1>", "utf8");

    const result = await (await getTool()).execute({
      output_file: "site.zip",
      directories: [
        {
          workspaceDir: "site",
          archiveDir: "website",
          includeGlobs: ["**/*.html"],
          excludeGlobs: ["**/draft.html"],
        },
      ],
    }, ctx());

    expect(result.success).toBe(true);
    expect(result.metadata?.["entryCount"]).toBe(3);

    const names = listZipEntryNames(join(workspace, "generated", "site.zip")).sort();
    expect(names).toEqual([
      "website/about.html",
      "website/docs/intro.html",
      "website/index.html",
    ]);
  });

  it("rejects archive paths containing '..'", async () => {
    const result = await (await getTool()).execute({
      output_file: "out.zip",
      inline: [{ archivePath: "../escape.txt", content: "x" }],
    }, ctx());
    expect(result.success).toBe(false);
    expect(result.error).toContain("..");
  });

  it("rejects duplicate archive paths across entries", async () => {
    writeFileSync(join(workspace, "a.txt"), "a", "utf8");
    const result = await (await getTool()).execute({
      output_file: "out.zip",
      inline: [{ archivePath: "a.txt", content: "b" }],
      files: [{ workspacePath: "a.txt" }],
    }, ctx());
    expect(result.success).toBe(false);
    expect(result.error).toContain("duplicate");
  });

  it("rejects workspacePath that escapes the workspace", async () => {
    const result = await (await getTool()).execute({
      output_file: "out.zip",
      files: [{ workspacePath: "../outside.txt" }],
    }, ctx());
    expect(result.success).toBe(false);
    expect(result.error).toContain("workspacePath");
  });

  it("refuses overwrite when overwrite=false and the file exists", async () => {
    await (await getTool()).execute({
      output_file: "out.zip",
      inline: [{ archivePath: "x.txt", content: "first" }],
    }, ctx());
    const second = await (await getTool()).execute({
      output_file: "out.zip",
      inline: [{ archivePath: "x.txt", content: "second" }],
      overwrite: false,
    }, ctx());
    expect(second.success).toBe(false);
    expect(second.error).toContain("Refusing");
  });
});
