import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { accountAllowsUser } from "../account-access.js";
import { createApp } from "../app.js";
import { readAccountsOverlay } from "../config.js";
import { LiveAccounts } from "../live-accounts.js";
import type { MailAccountConfig } from "../types.js";

/**
 * The isolation-only overlay document `pnpm e2e:setup` writes (config/mail/accounts.d/
 * 00-e2e-isolation.json5): no account of its own, only isolatedUsers. It must keep the e2e eval
 * identities off every shared account whenever the eval accounts exist — also while no GreenMail
 * account is in the overlay.
 */
const server = { host: "h", port: 993, secure: true, user: "u", pass: "p" };
const shared: MailAccountConfig = { id: "work", address: "team@example.com", imap: server, smtp: server };
const bound: MailAccountConfig = { id: "alice-only", address: "alice@example.com", allowedUsers: ["alice"], imap: server, smtp: server };

const ISOLATION_ONLY = [
  "// GENERATED by `pnpm e2e:setup`",
  JSON.stringify({ accounts: [], isolatedUsers: ["eval", "eval-viewer"] }, null, 2),
  "",
].join("\n");

describe("an isolation-only accounts overlay document", () => {
  let dir: string;
  let overlayDir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "starlingai-mail-isolation-"));
    overlayDir = join(dir, "accounts.d");
    mkdirSync(overlayDir);
    writeFileSync(join(overlayDir, "00-e2e-isolation.json5"), ISOLATION_ONLY);
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it("parses with an empty accounts list", async () => {
    const overlay = await readAccountsOverlay(overlayDir);
    expect(overlay.files).toEqual([{ file: "00-e2e-isolation.json5", document: { accounts: [], isolatedUsers: ["eval", "eval-viewer"] } }]);
  });

  it("withholds every shared account from the eval identities, and only from them", async () => {
    const live = new LiveAccounts({ accounts: [shared, bound], isolatedUsers: [] }, overlayDir, 0);
    await live.refresh();
    expect(live.list.map((account) => account.id)).toEqual(["work", "alice-only"]);
    const work = live.list.find((account) => account.id === "work")!;
    expect(accountAllowsUser(work, "eval")).toBe(false);
    expect(accountAllowsUser(work, "EVAL-VIEWER")).toBe(false);
    expect(accountAllowsUser(work, "alice")).toBe(true);

    // What the e2e preflight asks the running service: GET /api/accounts as X-Sai-User eval.
    const app = createApp({ accounts: live.list, store: {} as never, refreshAccounts: () => live.refresh() });
    const visibleTo = async (user: string): Promise<string[]> =>
      ((await (await app.fetch(new Request("http://m/api/accounts", { headers: { "X-Sai-User": user } }))).json()) as Array<{ id: string }>).map((account) => account.id);
    expect(await visibleTo("eval")).toEqual([]);
    expect(await visibleTo("eval-viewer")).toEqual([]);
    expect(await visibleTo("alice")).toEqual(["work", "alice-only"]);

    // Without the document, the shared account is everyone's again.
    rmSync(join(overlayDir, "00-e2e-isolation.json5"));
    expect(await visibleTo("eval")).toEqual(["work"]);
  });
});
