export type AuditEventType =
  | "session_created"
  | "session_ended"
  | "message_received"
  | "message_sent"
  | "tool_call_requested"
  | "tool_call_approved"
  | "tool_call_blocked"
  | "tool_call_completed"
  | "tool_call_failed"
  | "tool_output_blocked"
  | "guardrail_blocked"
  | "guardrail_flagged"
  | "output_redacted"
  | "auth_success"
  | "auth_failure"
  | "rate_limited"
  | "provider_health_check"
  | "provider_failover"
  | "provider_recovered"
  | "agent_message_sent"
  | "channel_delivery_failed"
  | "agent_routing_evaluated"
  | "credential_accessed"
  | "credential_fill"
  | "session_reset"
  | "sub_agent_started"
  | "sub_agent_completed"
  | "sub_agent_tool_call"
  | "sub_agent_tool_blocked"
  | "sub_agent_max_iterations"
  | "parallel_delegate_started"
  | "turn_performance"
  | "scene_job_completed"
  | "scene_job_failed"
  | "scene_job_cancelled"
  | "ephemeral_agent_rejected"
  | "approval_requested"
  | "approval_resolved"
  | "warden_alert"
  | "architect_fallback_started"
  | "architect_fallback_completed"
  | "architect_fallback_failed"
  | "architect_fallback_rejected"
  | "prompt_budget_exceeded"
  | "turn_guidance_applied"
  | "turn_slo_breach"
  | "computer_action"
  | "computer_screenshot_analyzed"
  | "computer_credential_prompt_detected"
  | "computer_session_started"
  | "computer_session_stopped"
  | "computer_session_emergency_stopped"
  | "computer_session_start"
  | "computer_session_attach"
  | "computer_session_stop"
  | "computer_session_emergency_stop"
  | "computer_heartbeat_lost"
  | "tool_loop_detected"
  // Tool development & self-improvement
  | "tool_dev_session_started"
  | "tool_dev_session_completed"
  | "tool_dev_session_terminated"
  | "tool_deployed"
  | "capability_gap_detected"
  | "capability_gap_proposal"
  | "self_improvement_completed"
  | "ephemeral_cleanup"
  | "warden:tool_dev_stuck"
  | "warden:tool_dev_runaway";

export interface AuditEvent {
  id: string;
  timestamp: string; // ISO 8601
  type: AuditEventType;
  sessionId?: string;
  userId?: string;
  channel?: string;
  data: Record<string, unknown>;
  severity: "info" | "warn" | "error";
}
