/**
 * Audit events emitted by core extensions, always namespaced
 * `<extension>.<event>` (e.g. "mfa.patient_data_accessed"). The dot keeps the
 * fork-owned namespace disjoint from the core union forever — extensions
 * declare their events in their manifest instead of editing this file.
 */
export type ExtensionAuditEventType = `${string}.${string}`;

export type AuditEventType = CoreAuditEventType | ExtensionAuditEventType;

export type CoreAuditEventType =
  | "extension_loaded"
  | "extension_load_failed"
  | "session_created"
  | "session_ended"
  | "serve_app_started"
  | "serve_app_running"
  | "serve_app_stopped"
  | "message_received"
  | "message_sent"
  | "tool_call_requested"
  | "tool_call_approved"
  | "tool_call_blocked"
  | "tool_call_completed"
  | "tool_call_failed"
  | "tool_call_recovered"
  | "tool_output_blocked"
  | "guardrail_blocked"
  | "guardrail_flagged"
  | "output_redacted"
  | "auth_success"
  | "auth_failure"
  | "rate_limited"
  | "provider_health_check"
  | "provider_failover"
  | "provider_recovered"
  | "model_preset_switched"
  | "anthropic_oauth_connected"
  | "anthropic_oauth_disconnected"
  | "agent_message_sent"
  | "channel_delivery_failed"
  | "agent_routing_evaluated"
  | "credential_accessed"
  | "credential_fill"
  | "session_reset"
  | "session_rewound"
  | "sub_agent_started"
  | "sub_agent_completed"
  | "sub_agent_soft_deadline"
  | "sub_agent_tool_call"
  | "sub_agent_tool_blocked"
  | "sub_agent_max_iterations"
  | "sub_agent_reasoning"
  | "agent_reasoning"
  | "parallel_delegate_started"
  | "parallel_delegate_deduplicated"
  | "delegated_deliverable_relayed"
  | "turn_performance"
  | "event_loop_lag"
  | "provider_stall"
  | "scene_job_completed"
  | "scene_job_failed"
  | "scene_job_cancelled"
  | "ephemeral_agent_rejected"
  | "ephemeral_tools_autofilled"
  | "artifact_completion_claim_unbacked_bannered"
  | "ephemeral_model_override_rejected"
  | "approval_requested"
  | "approval_resolved"
  | "warden_alert"
  | "architect_fallback_started"
  | "architect_fallback_completed"
  | "architect_fallback_failed"
  | "architect_fallback_rejected"
  | "prompt_budget_exceeded"
  | "prompt_section_sizes"
  | "history_compacted"
  | "session_memory_consolidated"
  | "memory_consolidation_sweep"
  | "memory_fact_superseded"
  | "task_budget_exceeded"
  | "turn_guidance_applied"
  | "turn_slo_breach"
  | "computer_action"
  | "computer_screenshot_analyzed"
  | "computer_credential_prompt_detected"
  | "computer_session_started"
  | "computer_session_stopped"
  | "computer_session_emergency_stopped"
  | "computer_session_start"
  | "computer_session_attach"
  | "computer_session_stop"
  | "computer_session_emergency_stop"
  | "computer_heartbeat_lost"
  // Browser session — noVNC live preview + human handoff
  | "browser_session_register"
  | "browser_session_assist_requested"
  | "browser_session_assist_resolved"
  | "browser_session_assist_timeout"
  | "browser_session_stop"
  // Long-running generation — pause/resume on big sub-agent runs
  | "long_running_generation_requested"
  | "long_running_generation_resolved"
  | "long_running_generation_timeout"
  | "long_running_generation_stopped"
  | "long_running_generation_auto_stopped"
  // Mid-turn user steering — fold user guidance into a running turn
  | "turn_steering_enqueued"
  | "turn_steering_injected"
  | "assistant_text_with_tool_calls_suppressed"
  | "tool_loop_detected"
  // Config proposals & self-improvement
  | "config_proposal_created"
  | "config_proposal_applied"
  | "config_proposal_rejected"
  | "self_improvement_applied"
  // Tool development & self-improvement
  | "tool_dev_session_started"
  | "tool_dev_session_completed"
  | "tool_dev_session_terminated"
  | "tool_deployed"
  | "tool_promotion_nominated"
  | "tool_promoted"
  | "tool_promotion_rejected"
  | "capability_gap_detected"
  | "capability_gap_proposal"
  | "gap_confirmed_closed"
  | "self_improvement_dev_started"
  | "self_improvement_completed"
  | "skill_authored"
  | "skill_distilled"
  | "skill_patched"
  | "skill_rolled_back"
  | "skill_outcome_recorded"
  | "skill_retired"
  | "skill_promoted_to_scene"
  | "user_model_updated"
  | "memory_curation_nudge"
  | "tool_pipeline_executed"
  | "ephemeral_cleanup"
  | "a2a_messages_delivered"
  | "task_checkpoint_created"
  | "task_checkpoint_paused"
  | "task_checkpoint_resumed"
  | "task_checkpoint_completed"
  | "delegate_agent_pinned"
  | "delegation_routing_filtered_artifact_incapable"
  | "delegation_bidding_filtered_artifact_incapable"
  | "delegation_routing_filtered_research_incapable"
  | "delegation_bidding_filtered_research_incapable"
  | "delegation_routing_filtered_capability_incapable"
  | "delegation_bidding_filtered_capability_incapable"
  | "delegation_bidding_filtered_meta_factory"
  | "delegation_explicit_redirected_research_incapable"
  | "delegation_render_research_redirect_skipped"
  | "delegation_routing_embedding_degraded"
  | "delegation_depth_ceiling_enforced"
  | "delegation_halted_operator_stop"
  | "delegation_halted_partial_evidence"
  | "delegation_coordinator_recursion_blocked"
  | "flow_plan_recorded"
  | "flow_verification_passed"
  | "flow_verification_repaired"
  | "flow_high_stakes_unverified"
  | "plan_approval_requested"
  | "plan_approval_resolved"
  | "unverified_source_sensitive_answer_caveated"
  | "warden:tool_dev_stuck"
  | "warden:tool_dev_runaway"
  // Infrastructure health
  | "docker_daemon_unreachable"
  // Observability
  | "turn_scorecard"
  | "coverage_shortfall_resynthesis"
  | "sub_agent_assistant_text_with_tool_calls_suppressed"
  | "sub_agent_tool_loop_detected"
  | "sub_agent_synthesis_forced"
  | "hallucinated_truncation_bypass"
  | "trajectory_cache_hit"
  | "trajectory_cache_used"
  | "trajectory_cache_invalidated"
  // Federation (Stage 11) — cross-instance delegation
  | "federation_auth_failed"
  | "federation_capabilities_served"
  | "federation_delegate_started"
  | "federation_delegate_completed"
  | "federation_delegate_failed"
  | "federation_delegate_denied"
  | "federation_request_received"
  | "federation_request_completed"
  | "federation_request_failed"
  | "federation_search_served"
  | "federation_search_started"
  | "federation_search_completed"
  | "federation_peer_discovered"
  | "federation_peer_unreachable"
  // Self-improvement abuse detection (closes GAP-4)
  | "tier_escalation_attempt"
  | "self_improve_loop"
  // Multi-user auth (Wave A) + RBAC (Wave B)
  | "auth_user_created"
  | "auth_user_deleted"
  | "rbac_denied"
  // Plugin SDK
  | "plugin_loaded"
  | "plugin_unloaded"
  | "plugin_tool_rejected"
  // Cost governance
  | "cost_budget_threshold"
  // Tool embedding warm-up (Stage 12 / Open Interop)
  | "tool_embeddings_warmed"
  // MCP client (consumed servers) — runtime registry
  | "mcp_server_added"
  | "mcp_server_updated"
  | "mcp_server_removed"
  | "mcp_server_reconnected"
  | "mcp_server_connect_failed"
  // MCP server (we expose ourselves as an MCP endpoint)
  | "mcp_server_request"
  | "mcp_server_tool_called"
  | "mcp_server_tool_rejected"
  | "mcp_server_session_opened"
  | "mcp_server_session_closed"
  // A2A — public Agent-to-Agent protocol
  | "a2a_request_received"
  | "a2a_request_failed"
  | "a2a_task_completed"
  | "a2a_peer_added"
  | "a2a_peer_removed"
  | "a2a_peer_unreachable";

export interface AuditEvent {
  id: string;
  timestamp: string; // ISO 8601
  type: AuditEventType;
  sessionId?: string;
  userId?: string;
  channel?: string;
  data: Record<string, unknown>;
  severity: "info" | "warn" | "error";
}
